### ISSUE TITLE
What's this, may I ask?

### ISSUE THREAD

**Issue by edwinyzh** [davidlastrucci/DelphiLive2020#1]
No readme, no wiki, What's this? Thanks.

**Comment by davidlastrucci** [comment]
Hello Edwin,
These are slides and examples that I presented to a Webinar entitled Windows Code Sign.

If you need clarification ask.

Thank you,
David Lastrucci

**Comment by edwinyzh** [comment]
Hello David,
Could you post the link to the slides? I did a google but failed to find it :)

**Comment by davidlastrucci** [comment]
Hi,
You can find them in the PDF file.

But they are in Italian language.
